# Generated by Django 2.1.7 on 2019-03-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notes_folder',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='course_slug',
            field=models.SlugField(null=True),
        ),
    ]
