# Generated by Django 2.1.7 on 2019-03-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_remove_course_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='title',
            field=models.CharField(max_length=46),
        ),
    ]
