# Generated by Django 2.1.7 on 2019-03-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_classnote_note_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnote',
            options={'ordering': ['-created_at', '-course']},
        ),
    ]
