# Generated by Django 2.1.7 on 2019-03-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_auto_20190317_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnote',
            options={},
        ),
    ]
