# Generated by Django 2.1.7 on 2019-03-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_auto_20190317_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='notes_folder',
            new_name='course_slug',
        ),
    ]
