# Generated by Django 2.1.7 on 2019-03-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_auto_20190317_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='course_slug',
            new_name='term_slug',
        ),
    ]
