# Generated by Django 2.1.7 on 2019-03-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_auto_20190317_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnote',
            options={'ordering': ['course', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code']},
        ),
        migrations.AlterField(
            model_name='classnote',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
