# Generated by Django 2.1.7 on 2019-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_auto_20190321_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
