# Generated by Django 2.1.7 on 2019-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_auto_20190406_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
