# Generated by Django 2.1.7 on 2019-04-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0015_auto_20190410_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
