# Generated by Django 2.1.7 on 2019-04-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_auto_20190410_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='term',
            name='school',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='term',
            name='session',
            field=models.CharField(max_length=40),
        ),
    ]
